sudo: false
language: java
jdk: oraclejdk8
env:
  - PROJECT_DIR=network-pong_maven TEST=asdf
  - PROJECT_DIR=character-editor_maven
  - PROJECT_DIR=muenzspiel_maven
  - PROJECT_DIR=fassspiel_maven
  - PROJECTS=network-pong_maven!character-editor_maven!muenzspiel_maven!fassspiel_maven
cache:
  directories:
  - "$HOME/.m2"
script: 
- cd $PROJECT_DIR
- mvn clean install -DskipTests=true 
- cp target/*-0.0.1-SNAPSHOT-jar-with-dependencies.jar target/$PROJECT_DIR.jar
deploy:
  provider: releases
  tag_name: "$TRAVIS_TAG"
  name: Spieleprogrammierung $TRAVIS_TAG
  api_key:
    secure: WwQKcmls+7plMbM3TlxYV76F62p2F0ylqIIOl5dMdRwxWxXgzNrb8pmIVFbbx6J8nBRv2GJF/Y83vWZq299rnHSaUAaKiwdXveVJSs+UFZ+VOqA/pLKYWN9rG0zC5Z3aVfmW3mNvoJ+X9UgiaEgG5GhML4muM3gNKEutsAUJ3yp57REwCIHdvnC0W6HVF0qEvusfIzaLc0n74v7kcwGkbzb0R30j5QIcl4dXEU8BP3n3yshMAR98rHGYeFmaAHrpTduiRTh7zXiNezHwMrEGvz4Wyzqn1QG8p8GiB5Cx+iV/lCuPgKA130JFgmWUXT3MocbjF5oas9zvdVFe1IHmWnSimafukRgc9G4cBoGyflVj0U6zbF4YwngRb4Z7wL1dFeDwp/oGz66YclQRJQeKpjOOzlG8Zs4jaL9zukN2vlL6eUkd9f/BRcJf5R1IqKje2E8OV2mwrHCcR6ZExI68lMHTyhKiKbodGiyQGLLbTRgAmnekqWATxiEHjylV1U6mNkitjpBtrJLtWUPAprDgj3oKi9+85tXoGqLrZWJhvVFuDF9wNAZa8Boc7RkJKqZDg0sBzdRNf3t03J31bgI3EzCP23xHHsj7UFxpo3xs1Z2+vbl/b/DRQatfCiY8sVtCwRSobK6EkriwelFkNlkvXeNCPkRnKrXkS26NZ2beIQ8=
  file: target/$PROJECT_DIR.jar
  skip_cleanup: true
  on:
    repo: ScholliYT/SpieleProgrammierung
    tags: true
